version: '3'

services:
  app:
    image: nifisample/app
    links:
      - app-postgre-db:app-postgre-db
    ports:
      - 80:80
    environment:
      - UploadUrl=Uploads
      - BackendRoot=https://localhost
      - DefConnStr=SERVER=app-postgre-db;User ID=flexberryuser;Password=jhv;Port=5432;database=appdb;
    networks:
      - nifisample

  app-postgre-db:
    image: nifisample/postgre-sql
    volumes:
      - NiFiSamplePostgreDb:/var/lib/pgsql/data/
    ports:
      - 5432:5432
    networks:
      - nifisample

  nifi:
    image: nifisample/nifi
    ports:
      - 8443:8443
    environment:
      # 4 characters min
      SINGLE_USER_CREDENTIALS_USERNAME: flexberryuser
      # 12 characters min
      SINGLE_USER_CREDENTIALS_PASSWORD: jhvjhvjhvjhv
    depends_on:
      - app-postgre-db
      - clickhouse-db
    networks:
      - nifisample

volumes:
  NiFiSamplePostgreDb:

networks:
  nifisample:
